INSERT INTO YayinEvleri (YayineviID, YayineviAdi, Adres, Ulke) VALUES (1, 'Kara Karga Yayınları', 'İstanbul, Türkiye', 'Türkiye');
INSERT INTO YayinEvleri (YayineviID, YayineviAdi, Adres, Ulke) VALUES (2, 'İthaki Yayınları', 'Ankara, Türkiye', 'Türkiye');
INSERT INTO YayinEvleri (YayineviID, YayineviAdi, Adres, Ulke) VALUES (3, 'Can Yayınları', 'İzmir, Türkiye', 'Türkiye');
INSERT INTO YayinEvleri (YayineviID, YayineviAdi, Adres, Ulke) VALUES (4, 'Metis Yayınları', 'Bursa, Türkiye', 'Türkiye');
INSERT INTO YayinEvleri (YayineviID, YayineviAdi, Adres, Ulke) VALUES (5, 'Alfa Yayınları', 'Antalya, Türkiye', 'Türkiye');
INSERT INTO YayinEvleri (YayineviID, YayineviAdi, Adres, Ulke) VALUES (6, 'İletişim Yayınları', 'Adana, Türkiye', 'Türkiye');
INSERT INTO YayinEvleri (YayineviID, YayineviAdi, Adres, Ulke) VALUES (7, 'Timaş Yayınları', 'Gaziantep, Türkiye', 'Türkiye');
INSERT INTO YayinEvleri (YayineviID, YayineviAdi, Adres, Ulke) VALUES (8, 'Yapı Kredi Yayınları', 'Konya, Türkiye', 'Türkiye');
INSERT INTO YayinEvleri (YayineviID, YayineviAdi, Adres, Ulke) VALUES (9, 'Dex Yayınları', 'Kayseri, Türkiye', 'Türkiye');
INSERT INTO YayinEvleri (YayineviID, YayineviAdi, Adres, Ulke) VALUES (10, 'Pegasus Yayınları', 'Sakarya, Türkiye', 'Türkiye');
